Repository OpenXiangShan/GEM5, pull requests merged in 2025-03, with the labels that each got.

#305 cpu-o3: consider rename in worst-case scenario
  src/cpu/o3/rename.cc
  src/cpu/o3/rename.hh
Labels: do not merge, calibration

#279 cpu-o3: add some comments for backend
  src/cpu/o3/iew.cc
  src/cpu/o3/iew.hh
  src/cpu/o3/issue_queue.cc
  src/cpu/o3/issue_queue.hh
  src/cpu/o3/lsq.cc
  src/cpu/o3/lsq_unit.cc
  src/cpu/o3/lsq_unit.hh
Labels: documentation

#314 cpu-o3: fix write port conflict
  src/cpu/o3/issue_queue.cc
  src/cpu/o3/issue_queue.hh
Labels: bug, calibration

#320 cpu-o3: read fflags should not serialize after
  src/arch/riscv/isa/decoder.isa
  src/cpu/o3/FuncUnitConfig.py
Labels: calibration

#316 mem: fix ruby `cacheSatisfied` bug
  src/mem/ruby/system/RubyPort.cc
  src/mem/ruby/system/Sequencer.cc
Labels: bug

#321 Revert split fma
  src/arch/riscv/insts/standard.cc
  src/arch/riscv/insts/standard.hh
  src/arch/riscv/isa/decoder.isa
  src/arch/riscv/isa/formats/fp.isa
  src/arch/riscv/isa/operands.isa
  src/arch/riscv/regs/int.hh
  src/cpu/FuncUnit.py
  src/cpu/o3/FuncUnitConfig.py
  src/cpu/o3/commit.cc
  src/cpu/o3/decode.cc
  src/cpu/o3/decode.hh
  src/cpu/o3/fetch.cc
  src/cpu/o3/iew.cc
  src/cpu/o3/iew.hh
  src/cpu/o3/issue_queue.cc
  src/cpu/o3/rename.cc
  src/cpu/o3/rob.hh
  src/cpu/op_class.hh
Labels: calibration

#319 Split statsd
  configs/common/FUScheduler.py
  src/arch/riscv/insts/mem.cc
  src/arch/riscv/insts/mem.hh
  src/arch/riscv/isa/decoder.isa
  src/cpu/FuncUnit.py
  src/cpu/StaticInstFlags.py
  src/cpu/o3/FuncUnitConfig.py
  src/cpu/o3/dyn_inst.cc
  src/cpu/o3/dyn_inst.hh
  src/cpu/o3/iew.cc
  src/cpu/o3/issue_queue.cc
  src/cpu/o3/issue_queue.hh
  src/cpu/o3/lsq_unit.cc
  src/cpu/o3/lsq_unit.hh
  src/cpu/o3/rename_map.hh
  src/cpu/op_class.hh
  src/cpu/static_inst.hh
Labels: calibration

#328 cpu-o3: load specwake each replay and STD forward not ready fast replay
  src/cpu/o3/FuncUnitConfig.py
  src/cpu/o3/iew.cc
  src/cpu/o3/iew.hh
  src/cpu/o3/inst_queue.cc
  src/cpu/o3/inst_queue.hh
  src/cpu/o3/issue_queue.cc
  src/cpu/o3/issue_queue.hh
  src/cpu/o3/lsq_unit.cc
  src/cpu/o3/lsq_unit.hh
Labels: calibration

#329 cpu-o3: disable storeset on kmhv2
  configs/example/xiangshan.py
  src/cpu/o3/BaseO3CPU.py
  src/cpu/o3/iew.cc
  src/cpu/o3/iew.hh
Labels: calibration

#326 mem: align xs stream/stride with RTL
  src/mem/cache/prefetch/xs_stream.cc
  src/mem/cache/prefetch/xs_stream.hh
  src/mem/cache/prefetch/xs_stride.cc
  src/mem/cache/prefetch/xs_stride.hh
Labels: calibration

#327 mem: align l2 bop config with rtl
  configs/common/PrefetcherConfig.py
  src/mem/cache/prefetch/Prefetcher.py
  src/mem/cache/prefetch/bop.cc
  src/mem/cache/prefetch/bop.hh
Labels: calibration

#335 cpu-o3: fix nuke replay & violation & fwd
  src/cpu/o3/lsq_unit.cc
Labels: bug, calibration

#334 cpu-o3: issue replayed inst first
  src/cpu/o3/dyn_inst.hh
  src/cpu/o3/issue_queue.cc
  src/cpu/o3/issue_queue.hh
Labels: calibration

#333 mem: align L1-L2 latency with RTL
  configs/common/Caches.py
Labels: calibration

#344 Revert "cpu-o3: change the condition of dispatchInst (#312)"
  src/cpu/o3/iew.cc
  src/cpu/o3/iew.hh
  src/cpu/o3/issue_queue.cc
  src/cpu/o3/issue_queue.hh
Labels: bug
